all:
  children:
    prod:
      hosts:
        client1:
          ansible_host: 192.168.99.11
          ansible_user: vagrant
          ansible_ssh_pass: vagrant
          ansible_sudo_pass: root
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
          welcome_message: "Bienvenue sur le serveur {{ ansible_hostname }}"
          port: 8090
        reverse_proxy:
          ansible_host: 192.168.99.12
          ansible_user: vagrant
          ansible_ssh_pass: vagrant
          ansible_sudo_pass: root
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
          welcome_message: "Bienvenue sur le serveur {{ ansible_hostname }}"
          port: 8090
    staging:
      hosts:
        client2:
          ansible_host: 192.168.99.12
          ansible_user: vagrant
          ansible_ssh_pass: vagrant
          ansible_sudo_pass: root
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
          welcome_message: "Bienvenue sur le serveur {{ ansible_hostname }}"
          port: 8090
    proxy:
      hosts:
        reverse_proxy:
          ansible_host: 192.168.99.12
          ansible_user: vagrant
          ansible_ssh_pass: vagrant
          ansible_sudo_pass: root
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
          welcome_message: "Bienvenue sur le serveur {{ ansible_hostname }}"
          port: 8090
